apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 2
  labels:
    app: worker
  name: worker
  namespace: voting-application

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: worker
    deploymentconfig: worker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: worker
        deploymentconfig: worker
    spec:
      containers:
      - image: docker-registry.default.svc:5000/voting-application/worker
        imagePullPolicy: Always
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - worker
      from:
        kind: ImageStreamTag
        name: worker:latest
        namespace: voting-application
      lastTriggeredImage: docker-registry.default.svc:5000/voting-application/worker@sha256:a18c33fac46c60766b07eef81d6b184082dc52ede1e088f6c639b546274925f4
    type: ImageChange
