apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-02-01T07:38:48Z"
  labels:
    app: result
  name: result
  namespace: voting-application
  resourceVersion: "52112"
  selfLink: /api/v1/namespaces/voting-application/services/result
  uid: e21605aa-44c5-11ea-bfc6-0242ac110037
spec:
  clusterIP: 172.30.241.130
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: result
    deploymentconfig: result
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
